api = 2
core = 7.58

projects[drupal][type] = core

projects[rules] = 2.10
projects[token] = 1.7
projects[variable] = 2.5
projects[views] = 3.18
projects[views_bootstrap] = 3.2
projects[services] = 3.20
projects[services_views] = 1.3
projects[pathauto] = 1.3
projects[physical] = 1.0
projects[message] = 1.12
projects[message_notify] = 2.5
projects[entity] = 1.9
projects[entityreference] = 1.5
projects[ctools] = 1.14
projects[commerce] = 1.14
projects[commerce_addressbook] = 2.0-rc9
projects[commerce_addressbook_extra] = 1.4
projects[commerce_flat_rate] = 1.0-beta2
projects[commerce_services] = 1.x-dev
projects[commerce_shipping] =2.3
projects[commerce_stock] =2.3
projects[commerce_stock_reserve] =1.4
projects[commerce_checkout_progress] = 1.5
projects[commerce_message] = 1.0
projects[search_api] = 1.23
projects[search_api_db] = 1.6
projects[facetapi] = 1.5
projects[facetapi_pretty_paths] = 1.4
projects[transliteration] = 3.2
projects[addressfield] = 1.2
projects[i18n] =1.22
projects[libraries] = 2.3
projects[ds] = 2.14
projects[panels] = 3.9
projects[file_entity] = 2.17
projects[media] = 2.16
projects[module_filter] = 2.1
projects[ckeditor] = 1.18
projects[bootstrap] = 3.19
projects[jquery_update] = 2.7
projects[imagecache_actions] = 1.9
